### ISSUE TITLE
Anchor links with "."

### ISSUE THREAD

**Issue by asindl** [ilyaplot/postgres-markdown#3]
Anchor links are auto-generated by substituting "." with a "-" (e.g. #### schema.table is referenced as (#schema-table).
In gitlab, a "." in a headline is simply left out in the anchor. So for me, the link then has to look like this (#schematable).

**Comment by ilyaplot** [comment]
I believe that a separator is still needed.

**Comment by ilyaplot** [comment]
@asindl you are right.
Dots was removed from anchor links.
