### ISSUE TITLE
I execute the command, nothing happened

### ISSUE THREAD

**Issue by gcdd1993** [ilyaplot/postgres-markdown#7]
i try 
```bash
postgres-markdown -H "192.168.2.23" -p 30002 -u "postgres" -W "olxin88" -l "en"
```

and 
```bash
postgres-markdown -H 192.168.2.23 -p 30002 -u postgres -W olxin88 -l en -o my.md
```

nothing happens, even output file or error messages, can you give me some suggestions? Thanks!

**Comment by ilyaplot** [comment]
@gcdd1993 try to install latest version and run again.
I added new option (--verbose). You can use this when nothing happens, thanks!
